use super::reference;
use codeatlas_domain::{EvidenceDocument, ScanReport, Symbol};

pub(crate) fn render_evidence(document: &EvidenceDocument) -> anyhow::Result<String> {
    document.validate()?;
    let mut output = String::new();
    output.push_str(&format!("# {}\n\n", escape_inline(&document.title)));
    output.push_str(&format!(
        "<!-- Generated by CodeAtlas {} reference documentation. Do not edit by hand. -->\n\n",
        escape_inline(&document.subject)
    ));
    if let Some(summary) = &document.summary {
        output.push_str(summary);
        output.push_str("\n\n");
    }
    for group in &document.groups {
        output.push_str(&format!("## {}\n\n", escape_inline(&group.name)));
        for section in &group.sections {
            output.push_str(&format!("### {}\n\n", escape_inline(&section.name)));
            for entry in &section.entries {
                output.push_str(&format!("#### {}\n\n", inline_code(&entry.name)));
                output.push_str(&format!("**Kind:** {}\n\n", escape_inline(&entry.kind)));
                if let Some(description) = &entry.description {
                    output.push_str(description);
                    output.push_str("\n\n");
                } else if let Some(missing) = &entry.missing_description {
                    output.push_str(&format!("> **Description unavailable:** {}\n\n", missing));
                }
                for fact in &entry.facts {
                    output.push_str(&format!(
                        "**{}:** {}\n\n",
                        escape_inline(&fact.label),
                        inline_code(&fact.value)
                    ));
                }
                for table in &entry.tables {
                    output.push_str(&format!("**{}**\n\n", escape_inline(&table.title)));
                    output.push('|');
                    for column in &table.columns {
                        output.push_str(&format!(" {} |", escape_table(column)));
                    }
                    output.push_str("\n|");
                    for _ in &table.columns {
                        output.push_str(" --- |");
                    }
                    output.push('\n');
                    for row in &table.rows {
                        output.push('|');
                        for value in row {
                            output.push_str(&format!(" {} |", escape_table(value)));
                        }
                        output.push('\n');
                    }
                    output.push('\n');
                }
                for note in &entry.notes {
                    output.push_str(&format!("> {}\n\n", note.replace('\n', "\n> ")));
                }
            }
        }
    }
    Ok(normalize_eof(output))
}

pub(crate) fn render(
    report: &ScanReport,
    title: Option<&str>,
    include_private: bool,
    public_name: Option<&str>,
) -> String {
    let reference = reference::build(report, title, include_private, public_name);

    let mut output = String::new();
    output.push_str(&format!("# {}\n\n", reference.title));
    output.push_str(&format!(
        "<!-- Generated by CodeAtlas {} using schema {}. Do not edit by hand. -->\n\n",
        report.tool_version, report.schema_version
    ));
    if let Some(package) = &report.package {
        output.push_str(&format!(
            "Package: `{}`",
            public_name.unwrap_or(&package.name)
        ));
        if let Some(version) = &package.version {
            output.push_str(&format!(" · Version: `{}`", version));
        }
        output.push_str("\n\n");
    }

    for group in reference.groups {
        output.push_str(&format!("## `{}`\n\n", group.name));
        for section in group.sections {
            output.push_str(&format!(
                "### {}\n\n",
                reference::kind_plural_label(section.kind)
            ));
            for symbol in section.symbols {
                render_symbol(
                    &mut output,
                    symbol,
                    4,
                    public_name.is_none(),
                    include_private,
                );
            }
        }
    }

    normalize_eof(output)
}

fn normalize_eof(mut output: String) -> String {
    while output.ends_with('\n') {
        output.pop();
    }
    output.push('\n');
    output
}

fn render_symbol(
    output: &mut String,
    symbol: &Symbol,
    heading_level: usize,
    show_exports: bool,
    include_private: bool,
) {
    let heading = "#".repeat(heading_level.min(6));
    output.push_str(&format!("{} `{}`\n\n", heading, symbol.name));
    output.push_str(&format!("**Kind:** {}", reference::kind_label(symbol.kind)));

    if show_exports && symbol.export_paths.len() > 1 {
        let paths = symbol
            .export_paths
            .iter()
            .map(|path| format!("`{}`", path))
            .collect::<Vec<_>>()
            .join(", ");
        output.push_str(&format!(" · **Exports:** {}", paths));
    }
    output.push_str("\n\n");

    if let Some(docs) = &symbol.docs {
        if let Some(reason) = &docs.deprecated {
            if reason.is_empty() {
                output.push_str("**Deprecated.**\n\n");
            } else {
                output.push_str(&format!("**Deprecated:** {}\n\n", reason));
            }
        }
        if let Some(stability) = docs.stability {
            output.push_str(&format!(
                "**Stability:** {}\n\n",
                reference::stability_label(stability)
            ));
        }
        if !docs.summary.is_empty() {
            output.push_str(&docs.summary);
            output.push_str("\n\n");
        }
        if let Some(remarks) = &docs.remarks {
            output.push_str(remarks);
            output.push_str("\n\n");
        }
    }

    output.push_str(&format!(
        "```{}\n{}\n```\n\n",
        reference::language_tag(symbol.language),
        symbol.signature
    ));

    if let Some(docs) = &symbol.docs {
        if !docs.params.is_empty() {
            output.push_str("**Parameters**\n\n| Name | Description |\n| --- | --- |\n");
            for (name, description) in &docs.params {
                output.push_str(&format!(
                    "| `{}` | {} |\n",
                    escape_table(name),
                    escape_table(description)
                ));
            }
            output.push('\n');
        }
        if let Some(returns) = &docs.returns {
            output.push_str(&format!("**Returns:** {}\n\n", returns));
        }
        for thrown in &docs.throws {
            output.push_str(&format!("**Throws:** {}\n\n", thrown));
        }
        if let Some(since) = &docs.since {
            output.push_str(&format!("**Since:** `{}`\n\n", since));
        }
        for example in &docs.examples {
            output.push_str(&format!(
                "**Example**\n\n```{}\n{}\n```\n\n",
                reference::language_tag(symbol.language),
                example
            ));
        }
    }

    if reference::uses_member_table(symbol, include_private) {
        render_member_table(
            output,
            reference::included_children(symbol, include_private),
        );
        render_member_examples(
            output,
            reference::included_children(symbol, include_private),
        );
    } else {
        for child in reference::included_children(symbol, include_private) {
            render_symbol(output, child, heading_level + 1, false, include_private);
        }
    }
}

fn render_member_examples<'a>(output: &mut String, members: impl Iterator<Item = &'a Symbol>) {
    for member in members {
        let Some(docs) = &member.docs else { continue };
        for example in &docs.examples {
            output.push_str(&format!(
                "**Example: {}**\n\n```{}\n{}\n```\n\n",
                inline_code(&escape_table(&member.name)),
                reference::language_tag(member.language),
                example
            ));
        }
    }
}

fn render_member_table<'a>(output: &mut String, members: impl Iterator<Item = &'a Symbol>) {
    output.push_str("**Members**\n\n| Member | Signature | Description |\n| --- | --- | --- |\n");
    for member in members {
        let description = reference::member_description(member);
        output.push_str(&format!(
            "| {} | {} | {} |\n",
            inline_code(&escape_table(&member.name)),
            inline_code(&escape_table(&member.signature)),
            escape_table(&description)
        ));
    }
    output.push('\n');
}

fn escape_table(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br>")
}

fn inline_code(value: &str) -> String {
    let fence = "`".repeat(
        value
            .split(|character| character != '`')
            .map(str::len)
            .max()
            .unwrap_or(0)
            + 1,
    );
    format!("{}{}{}", fence, value, fence)
}

fn escape_inline(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace('*', "\\*")
        .replace('_', "\\_")
        .replace('[', "\\[")
        .replace(']', "\\]")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::{escape_table, inline_code, normalize_eof};

    #[test]
    fn escapes_markdown_tables() {
        assert_eq!(escape_table("one | two\nthree"), "one \\| two<br>three");
        assert_eq!(inline_code("`template`"), "```template```");
    }

    #[test]
    fn keeps_exactly_one_trailing_newline() {
        assert_eq!(normalize_eof("reference\n\n".to_owned()), "reference\n");
    }
}
